name: Packeto
website: https://github.com/Snowiiii/Packeto
version: '${version}'
description: '${description}'
main: de.snowii.packeto.PacketoPlugin
api-version: 1.13
author: snowii
softdepend:
  - ProtocolSupport
  - ViaVersion
  - Geyser-Spigot